language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
 - 5.6
 - 7.0

matrix:
 allow_failures:
  - php: 7.0

env:
 matrix:
  - DB=pgsql MOODLE_BRANCH=MOODLE_29_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_30_STABLE
  - DB=pgsql MOODLE_BRANCH=master
  - DB=mysqli MOODLE_BRANCH=MOODLE_29_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_30_STABLE
  - DB=mysqli MOODLE_BRANCH=master

before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev moodlerooms/moodle-plugin-ci ci ^1
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

  # Cloning the local_inscricoes.
  - git clone https://github.com/UFSC/moodle-local-inscricoes.git local/inscricoes

  # Running the scripts to install and upgrade the database
  - php admin/cli/install_database.php --agree-license --adminpass=Password --adminemail=admin@example.com --fullname="Upgrade test" --shortname=Upgrade;
  - php admin/cli/upgrade.php --non-interactive --allow-unstable ;

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint || true
  - moodle-plugin-ci phpcpd || true
  - moodle-plugin-ci phpmd || true
  - moodle-plugin-ci codechecker || true
  - moodle-plugin-ci csslint || true
  - moodle-plugin-ci shifter || true
  - moodle-plugin-ci jshint || true
  - moodle-plugin-ci validate || true
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
